### PR TITLE
Basic autotests added, public API names made more consistent.

### PR DESCRIPTION
**Pull request by hsa-online**
I added a sample test cases (using 'Catch' framework).
Also it seems the names of public API are now looking more consistent.

And the Test 3 now fails because the library doesn't like negative value in am_edit_suggest()

What do you think?

### CODE REVIEW

**Comment by starwing** [comment]
eh...

This is a Lua-style C library, so "heavily" naming is not very suit it's style :-(

and the test... I mean, I will add something like https://travis-ci.com/ to auto run current test when every commit, but not meaning use a test framework to run many tests.

for bugs, I will add https://coveralls.io/ support to this repo, to make 100% coverage test. this will eliminate  most of bugs.

so, sorry for we can not use your request... but still very thank you for help improve our code :-)

**Comment by hfossli** [comment]
@starwing can you explain why this naming isn't better? It seems a lot better for autocompletion and IDE's.

**Comment by starwing** [comment]
@hfossli this naming indeed better, it's more clear. but for autocomplete for IDE's, naming without same prefix may better.

the original naming of amoeba has the style of [Lua language API](https://www.lua.org/manual/5.3/#index),  this is the original purpose for amoeba library: a extension module for Lua (and my GUI framework, [nui](https://github.com/starwing/nui) ). amoeba has few APIs to complete it's work, so IMHO i think we needn't use a serious naming :-)

**Comment by hsa-online** [comment]
Ok, no problem.

**Pull request closed without merging**
